theme: minima
title: Little Big Engineer
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#theme: jekyll-theme-minimal

#for 'minima' theme
header_pages:
     - tech_blog.html
     - research_summary.html
     - reading_notes.html
  